name: CI-CD

on:
  push:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Digital Ocean
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: bash kapischool-front/deploy.sh
          username: root
          host: ${{ secrets.SANDBOX_HOST }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
